# Generated by Django 3.1.5 on 2024-12-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
