# Generated by Django 3.1.5 on 2024-12-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='is_favorite',
            new_name='favorite',
        ),
    ]
